# Site settings
title: TransomJS
email: your-email@domain.com
description: >
  The Rapid API development framework.

baseurl: "/myTransom" # /jekyll-doc-theme the subpath of your site, e.g. /blog/
url: https://4umfreak.github.io/myTransom # the base hostname & protocol for your site
git_address: https://github.com/4umfreak/myTransom
git_edit_address: https://github.com/4umfreak/myTransom/blob/master

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
